### ISSUE TITLE
自签证书一直没有配好

### ISSUE THREAD

**Issue by LJYes** [pluosi/app-host#10]
自签证书是在docker文件夹里的nginx.conf文件里配置吗？配了快一天了，也没有配好，能不能帮发一个生产环境的nginx.conf文件里的配置

这是我的配置：
upstream app {
    server 52.35.117.51;
}

server {
    listen       443 ssl;
    listen 8686;
    server_name 52.35.117.51:3000;
    root /app/public;
    access_log test.access_log;
    ssl on;
    ssl_certificate www.infoljj.com.crt;
    ssl_certificate_key www.infoljj.com.key;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDH:AES:HIGH:!aNULL:!MD5:!ADH:!DH;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    index index.html index.htm;
    error_page  404              /404.html;
    error_page  500 502 503 504  /500.html;
    keepalive_timeout 60;

    client_max_body_size 1000m;

    location ~ ^/(assets|uploads)/  {
        gzip_static on;
        expires max;
        add_header Cache-Control public;
        break;
    }
    location / {
        proxy_redirect    off;
        proxy_set_header  Host             $http_host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;

        if (!-f $request_filename) {
            proxy_pass http://app;
        }
    }
}

**Comment by iBcker** [comment]
nginx 部署在外面，docker 里的东西不用动

给你个参考

```
server {
    listen 443 ssl;
    server_name  ota.xxx.com;

    access_log /var/log/nginx/ota.xxx.com_access.log;
    ssl_certificate /etc/letsencrypt/live/ota.xxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ota.xxx.com/privkey.pem; # managed by Certbot

    ssl on;

    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass http://192.168.66.248:3000;  #docker 服务的地址
    }
}

server {
    listen 80;
    server_name ota.xxx.com;
    rewrite ^(.*)$  https://$host$1 permanent;
}
```

**Comment by NoPPT** [comment]
@iBcker   这样的话iOSAPP在下载的时候下载地址会是http://192.168.66.248:3000/paks/11/manifest.plist 这个地址不是https的啊，无法下载的。
