### ISSUE TITLE
windows CMD curl上传文件自定义名称包含中文字符会乱码

### ISSUE THREAD

**Issue by devcxm** [pluosi/app-host#100]
windows 7系统默认编码是GBK，在命令行工具使用curl上传中文名称出现乱码，期望作者有时间去看下这问题。

**Comment by iBcker** [comment]
https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8

**Comment by devcxm** [comment]
> https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8

我知道可以更改系统的默认编码，但不能从服务端解决这个问题吗？我自己操作还好，但是让团队的所有成员进行这个操作就太麻烦了。

**Comment by iBcker** [comment]
如果有必要的话，可以自己改下代码，这种就不做支持了。
修改点：

`pkgs_controller.rb` 的 api_create 方法里的赋值部分 :

`pkg = Pkg.new({file:params[:file], user_id:user.id, plat_id:plat.id, file_nick_name:params[:file_nick_name],features:params[:features]})`

改为：

`pkg = Pkg.new({file:params[:file], user_id:user.id, plat_id:plat.id, file_nick_name:params[:file_nick_name].force_encoding("utf-8"),features:params[:features].force_encoding("utf-8")})`

**Comment by iBcker** [comment]
我没有 window 环境验证，所以你可试试

**Comment by devcxm** [comment]
不行，会报以下错误，算了，不弄了。

>  Failed to convert {"error":"invalid byte sequence in UTF-8"}
