### ISSUE TITLE
此网站无法提供安全链接

### ISSUE THREAD

**Issue by henlei153** [pluosi/app-host#102]
![image](https://user-images.githubusercontent.com/48276442/81269784-6ac71d80-907c-11ea-8a42-ed0ecc3abc68.png)

**Comment by henlei153** [comment]
我使用了caddy配置https，代理到app-host,然后提示我链接不安全

**Comment by henlei153** [comment]
我重新安装了，使用ip+端口方式登陆，点击管理没有反应

**Comment by henlei153** [comment]
![image](https://user-images.githubusercontent.com/48276442/81278716-a23bc700-9088-11ea-863d-9bd0c4cc046e.png)

**Comment by iBcker** [comment]
1. https 不要跟端口号，证书也得配对
2. 登录一下，不登录怎么管理·······

**Comment by henlei153** [comment]
> 1. https 不要跟端口号，证书也得配对
> 2. 登录一下，不登录怎么管理·······

是这样的
1.我访问的时候没有加端口号，当我点击下载的时候自动跳转3000端口了
2.我重新安装后没有账户登陆不了啊，管理哪里不是注册吗？

**Comment by iBcker** [comment]
1. 端口号改下  settings.local.yml
2. 第一个注册的帐号就是管理员
