### ISSUE TITLE
api上传包可以帮忙写个例子吗，谢谢

### ISSUE THREAD

**Issue by aslanTT** [pluosi/app-host#11]

**Comment by iBcker** [comment]
api token 那个页面里有一个curl的demo
USEGAE:

curl --form plat_id=34 --form file_nick_name=file_nick_name(可选) --form token=xxxx --form file=@/xx/xx.ipa https://ota.pluosi.com/api/pkgs

**Comment by iBcker** [comment]
其他语言的用法其实就是构建 Multipart/form-data 的 post 提交，传入file_nick_name和token和file就好了， :-)

**Comment by aslanTT** [comment]
多谢

**Comment by Domlaa** [comment]
> api token 那个页面里有一个curl的demo USEGAE:
> 
> curl --form plat_id=34 --form file_nick_name=file_nick_name(可选) --form token=xxxx --form file=@/xx/xx.ipa https://ota.xxx.com/api/pkgs

请问 plat_id=34 是怎么确定值的呢
