### ISSUE TITLE
我得到了这样的错误

### ISSUE THREAD

**Issue by tangguoan** [pluosi/app-host#111]
![image](https://user-images.githubusercontent.com/12583337/99859778-0dd02680-2bcc-11eb-9f27-8da93651d23a.png)

**Comment by tangguoan** [comment]
The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.

If you are the application owner check the logs for more information.

**Comment by tangguoan** [comment]
Request URL: http://10.0.0.122:3000/users
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 10.0.0.122:3000
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 1705
Content-Type: text/html; charset=UTF-8
Date: Sat, 21 Nov 2020 01:18:26 GMT
Server: nginx/1.14.2
X-Request-Id: 08470035-cdb6-4126-af53-03f9575711b9
X-Runtime: 0.020473



新建用户的时候发想了 422 错误码

**Comment by markgz** [comment]
碰到同样的问题，请问有什么解决方法吗？

**Comment by tangguoan** [comment]
> 碰到同样的问题，请问有什么解决方法吗？

我也没有解决,对这种开发语音不熟悉

**Comment by wolimomomo** [comment]
我也遇到这个问题是用docker 部署到

**Comment by hanlyjiang** [comment]
分享我遇到后解决的方式：

docker ps 查看：   

```
11968320c4ce        local_pluosi/app_host:0.1.1                                        "/bin/sh -c '/bin/ba…"   3 seconds ago       Up 2 seconds           0.0.0.0:3000->8686/tcp   app_host
```

注意 端口映射的 `0.0.0.0:3000->8686/tcp`的地方，这个地方的8686实际上是有问题的，可以修改docker/launcher 文件，将其中的 8686改成 3000 之后再运行。

或者直接运行：

```
docker stop app_host ;
docker rm app_host
docker run --restart always -it -d --name app_host -h app_host -v /mnt/data/deploy/app-host/shared:/app/shared -p 3000:3000 local_pluosi/app_host:0.1.1
```

**Comment by iBcker** [comment]
https://github.com/pluosi/app-host/issues/26

**Comment by gkl1368** [comment]
同这个问题，带了nginx就不行
