### ISSUE TITLE
https问题

### ISSUE THREAD

**Issue by gkl1368** [pluosi/app-host#115]
配置了nginx https后 第一次登陆就报这个错误
![image](https://user-images.githubusercontent.com/12904884/107332812-9d141880-6aef-11eb-94d4-2240385a00c3.png)

用的是docker版本，nginx里也添加了proxy_set header

**Comment by gkl1368** [comment]
问题找到了 外部nginx 必须加proxy_set_header X-Forwarded-Ssl on;

**Comment by iBcker** [comment]
哈哈哈，good
