### ISSUE TITLE
请教，在哪里把IP地址修改为自己的域名？

### ISSUE THREAD

**Issue by ai371908858** [pluosi/app-host#117]
您好，为解决证书问题，我在服务器部署后，绑定了域名，但是在下载apk时，链接变也了local:3000，而不是我绑定的域名链接，请问需要修改哪个配置文件？我的部署环境是使用的第二种方法， Docker 自己编译部署的，

**Comment by iBcker** [comment]
自动取的请求里的 host

**Comment by ai371908858** [comment]
不好意思，比较小白，方便说一下是哪个文件吗,辛苦了！
