### ISSUE TITLE
部署后，找不到asset文件夹

### ISSUE THREAD

**Issue by LJYes** [pluosi/app-host#12]
部署后，找不到asset文件夹
![image](https://user-images.githubusercontent.com/18663185/34765878-9cb86d44-f62d-11e7-9a2a-c6e0e7273cb7.png)
点击，登陆 或者 新建

会跳到报错页面
![image](https://user-images.githubusercontent.com/18663185/34766408-3eea9cd0-f62f-11e7-801f-77353df986bf.png)

整个app-host项目里的配置都没有动，包括`PROTOCOL` 和 `HOST`也没有改

我的外部nginx配置：
![image](https://user-images.githubusercontent.com/18663185/34766366-1a9e031c-f62f-11e7-8c38-92b1ce09d91c.png)
是不是需要我改 app-host 项目里的 docker/nginx.conf文件的配置，或者更改 config/settings.local.yml文件里的`HOST`？

**Comment by iBcker** [comment]
docker/nginx.conf是给 docker 用的，你不用理会
如果你用 docker 部署，应该没这个问题
如果你自己部署，那你这个 nginx 写错了

看这里 #5

**Comment by LJYes** [comment]
我是用 docker 部署的。
1、docker 内部的 nginx 没有修改
2、settings.local.yml 里的 PROTOCOL 和 HOST也没有改
3、上面那张图，是服务器的 nginx 的配置，位置在 etc/nginx/nginx.conf 

问：
1、外部的 nginx 是否要设置 root 之类的配置，来指定 docker 内部的 asset
2、由于现在域名尚在备案中，无法验证 https 是否有这样的问题，不知道改成https协议后，是否会解决这样的问题

不知道能否联系您，以获取帮助。这是我的qq：614281588

**Comment by LJYes** [comment]
我把项目删除了，然后重新部署。

在安装依赖的的时候 ./docker/launcher bootstrap -v ，发现了问题：
![image](https://user-images.githubusercontent.com/18663185/34807391-8bcc5310-f6c3-11e7-9572-b525e10256a1.png)


这可能是导致我之前出现的问题，不知道您怎么看？ 有没有好的办法解决？

**Comment by iBcker** [comment]
如果是 docker 部署，docker 里面的 nginx 不要动，外部的 nginx 就配成这个提供的例子就好了 #5
