### ISSUE TITLE
请问如何配合fastlane直接上传呢？

### ISSUE THREAD

**Issue by LittleXu** [pluosi/app-host#120]
curl --form plat_id=34 --form file_nick_name=file_nick_name(可选) --form token=***** --form features=features(可选) --form file=@/xx/xx.ipa ****

这一句是在terminal里面中执行的吗？ 怎样把它写到fastlane里面一键上传呢？

**Comment by iBcker** [comment]
fastlane 用的是 ruby 语言，可以在 Fastfile 里写 ：
system("curl --form plat_id=34 --form file_nick_name=file_nick_name(可选) --form token=***** --form features=features(可选) --form file=@/xx/xx.ipa ****")
