### ISSUE TITLE
计划适配 aab 安转包，求安装包用例

### ISSUE THREAD

**Issue by iBcker** [pluosi/app-host#127]
google 计划把 apk 改为 aab 格式，所以计划进行跟进适配，不过目前网络上还下载不到 aab 格式的安卓安装包

所以在此求助一下，如有小伙伴的 app 不涉密的，求发一份 aab 格式的安装包（最好带上一版 apk，方便我对比），万分感谢

to   ibcker#me.com

**Comment by Tuccuay** [comment]
[AppHostAABSample.zip](https://github.com/pluosi/app-host/files/6837329/AppHostAABSample.zip)

感恩🙏

**Comment by iBcker** [comment]
从原理上来看，应该开发者自己完成转换工作，所以暂时关闭此计划
https://developer.android.com/studio/command-line/bundletool
