### ISSUE TITLE
找不到plat_id=34

### ISSUE THREAD

**Issue by aslanTT** [pluosi/app-host#13]
curl --form plat_id=34 --form file_nick_name=xxx --form token=babe90b67a761a1aafdff1f27e3e301b2a65ccc9 --form file=@xxx.ipa http://123.57.229.36:3000/api/pkgs        
                                              
{"error":"Couldn't find Plat with 'id'=34 [WHERE \"plats\".\"deleted_at\" IS NULL]"}

**Comment by aslanTT** [comment]
忽略。。知道问题了

**Comment by brave723** [comment]
我今天遇到这个问题了，怎么处理的呢？
