### ISSUE TITLE
包多了之后性能急剧下降，很不稳定

### ISSUE THREAD

**Issue by bilinxing** [pluosi/app-host#137]
我是用docker部署的。0.2.3版本
大概上传了4、5白个包，平均每个包130m左右，访问变得很不稳定，页面反应很慢，有时候还打不开，还有上传文件时超时。
页面半天不动，比较高的概率出现如下报错：
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
然后去看docker日志，只有这些：
[....] Starting nginx: nginx[ ok .

Puma starting in single mode...

* Version 3.12.6 (ruby 2.5.1-p57), codename: Llamas in Pajamas

* Min threads: 3, max threads: 10

* Environment: production

/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE

/usr/local/bundle/gems/rack-2.2.3/lib/rack/multipart/parser.rb:12: warning: previous definition of BUFSIZE was here

* Listening on tcp://0.0.0.0:3000

Use Ctrl-C to stop

又没有任何报错，查看nginx日志会发现有大量500，400和如下报错信息：
38#38: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: 0.0.0.0,

目前怀疑是包传多了之后导致性能下降，是否能提供排查方法，以便排查性能瓶颈。或者是否有什么性能限制的参数可以配置？

**Comment by tinyc-z** [comment]
加点内存吧，cpu 最好两核以上，我司2w+个包，页面秒开

**Comment by bilinxing** [comment]
4核16g内存的服务器，跑个分发包应用，配置还行吧
