### ISSUE TITLE
docker部署下载地址总是localhost:3000

### ISSUE THREAD

**Issue by NoPPT** [pluosi/app-host#14]
已经在 `config/settings.local.yml` 中 修改`PROTOCOL` 和 `HOST` 为 `IP`地址

**Comment by NoPPT** [comment]
之前运行第一事件没有修改 `HOST`,运行之后在修改 `HOST`，然后重新运行
```
./docker/launcher rebuild
./docker/launcher restart
```
没效果，重新clone代码后第一时间修改`HOST`就可以了，

**Comment by jamesliao333** [comment]
兄弟，我同样遇到这个问题，请问你是怎么解决的呢？

**Comment by NoPPT** [comment]
@jamesliao333  我是通过 `./docker/launch ssh` 进入docker , 然后找到 `config.local.yml`文件，通过 `sed` 替换文本内容 http://www.runoob.com/linux/linux-comm-sed.html  ,然后在重新启动项目。

**Comment by pluosiapp** [comment]
docker 是 3000不影响的，因为你要自己挂 nginx，别直接依赖 docker，不然 https 证书你咋配。
