### ISSUE TITLE
没有固定最新版下载页的地址吗？

### ISSUE THREAD

**Issue by AoEiuV020** [pluosi/app-host#144]
蒲公英和firim之类都是地址固定的，上传新包也不换地址，
希望能加上这个，

**Comment by tinyc-z** [comment]
有看下 api，好像叫
:plant_id/latest

**Comment by AoEiuV020** [comment]
@tinyc-z 不是说api， 是说网页，有没有办法获取最新版的网址？
比如http://example.com/helloDemo 
然后网址分享出去后别人可以保存书签，我这边每次更新版本他依然可以用这个地址下载到最新版本，

**Comment by tinyc-z** [comment]
最新版网页和 api 都有 @AoEiuV020

**Comment by AoEiuV020** [comment]
@tinyc-z 抱歉我还是没有找到，能不能举个例子？建议更新到README.md中，
比如我现在一个app的版本列表页面地址是，
http://localhost:3000/apps/1/plats/1
然后最新版本下载页面地址是，
http://localhost:3000/pkgs/3
上传更新之后，最新版本下载页面地址是，
http://localhost:3000/pkgs/4
然后我的问题是，这个下载页面地址发生了变化，
那么是否存在一个地址会始终重定向到最新版本下载页面，可以提供给不懂技术的别人测试，
不是获取最新版本号的api，也不是获取最新下载页面地址的api，是能直接在浏览器打开的网页地址，

**Comment by tinyc-z** [comment]
web page:
http://localhost:3000/plats/1/latest
or api:
http://localhost:3000/api/plats/1/latest

**Comment by AoEiuV020** [comment]
@tinyc-z 刚试了下，不行，报错“The page you were looking for doesn't exist.”
有没有版本要求？我用的是docker上的版本tinyc/app-host:lastest

![image](https://user-images.githubusercontent.com/11682198/157198801-9688cf45-2fd7-4d52-a5d1-0a00af9c92fe.png)

**Comment by tinyc-z** [comment]
尴尬。。才记起来，在 develop 分支上，哈哈哈哈
