### ISSUE TITLE
安装依赖，报错

### ISSUE THREAD

**Issue by LJYes** [pluosi/app-host#15]
执行 `./docker/launcher bootstrap -v` 后，一直在 `Step 14 : RUN rake assets:precompile` 里报错。

![image](https://user-images.githubusercontent.com/18663185/34862943-db7b30a4-f7a7-11e7-8c4c-fc8a1635b454.png)

重新 `clone`  和 `编译` 了很多遍，开了 VPN 也一样报错。

启动后，出现找不到 `css` 和 `js` 文件。

![image](https://user-images.githubusercontent.com/18663185/34863802-3d6bdd78-f7ac-11e7-8852-92d43ef57a92.png)

查看目录，没有发现`public`文件夹。

![image](https://user-images.githubusercontent.com/18663185/34866568-f4e92720-f7b7-11e7-8267-0a09719a3a0c.png)
![image](https://user-images.githubusercontent.com/18663185/34866587-06706fbc-f7b8-11e7-9ff0-3d554b741ea9.png)

`shared` 文件夹里的也没有`css`和`js`文件

![image](https://user-images.githubusercontent.com/18663185/34866729-82fa4198-f7b8-11e7-9542-07bbf517451a.png)

已经部署一周了，能力有限，一直没有部署成功，希望能得到您的帮助，感谢！

**Comment by iBcker** [comment]
这个报错忽略。
看我以前给你的回答，不用再开新问题了

**Comment by LJYes** [comment]
多谢帮助！

**Comment by LJYes** [comment]
已经解决了资源不能访问的问题。
![image](https://user-images.githubusercontent.com/18663185/34873360-c7ca216e-f7cf-11e7-84b6-2edecd0a88ac.png)

**Comment by iBcker** [comment]
后来的人忽略楼上的答案。此项不用改

**Comment by LJYes** [comment]
目前遇到的问题：

手机扫码，无法下载。 
iOS会弹窗，无法连接到"39.106.210.xx" ；
安卓会显示下载失败。

iOS 截图 :

![image](https://user-images.githubusercontent.com/18663185/34904152-a6a23ac0-f87a-11e7-8cc8-8538a44f969f.png)


电脑端浏览器可以下载

![image](https://user-images.githubusercontent.com/18663185/34904131-3b06afbc-f87a-11e7-871a-7ceec8f3c0fe.png)

**Comment by iBcker** [comment]
安卓为什么要下 iOS 的包？

**Comment by iBcker** [comment]
iOS 打不开原因是你证书是自签名的，iPhone 上得安装 对应的 cer

**Comment by LJYes** [comment]
你好，我在手机上安装了签名证书，依旧显示无法连接到"39.106.210.84"。

`settings.local.yml`文件的配置：

```
PROTOCOL: "https://"
HOST: "39.106.210.84"
```

nginx.conf文件的配置:

```
server {
      listen 443 ssl;
      server_name 39.106.210.84;

      access_log /var/log/nginx/https_access.log;
      ssl_certificate /etc/encrypt/39.106.210.84.crt; # managed by Certbot
      ssl_certificate_key /etc/encrypt/39.106.210.84.key; # managed by Certbot

      ssl on;

      location / {
        proxy_set_header        Host $host:443;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:3000;  #docker 服务的地址
        proxy_redirect  default;
      }
    }

   server {
    listen 80;
    server_name 39.106.210.84;
    rewrite ^(.*)$  https://$host$1 permanent;
   }
```

iOS的证书已经下载并添加信任：

![image](https://user-images.githubusercontent.com/18663185/34968226-1f50f180-faa3-11e7-9c8f-a818f0ad3ec2.png)

**Comment by yuxingxin** [comment]
@LJYes 有一个注意的地方是第一次下载安装之前，需要先安装根证书，在安装完证书以后，在设置->通用->关于本机->证书信任设置 中对安装的根证书启用“完全信任”，这样才可以连接到服务器去下载App

**Comment by LJYes** [comment]
@yuxingxin 我已经安装了根证书，也添加了信任。

**Comment by yuxingxin** [comment]
第一，你确认下是否在关于本机里面设置的完全信任，第二，你检查下你的证书生成是否有问题，出现无法链接服务器，问题就是出在证书上面

**Comment by LJYes** [comment]
@yuxingxin 谢谢你的回答 ，我重新生成一个证书试一下

**Comment by yuxingxin** [comment]
确认证书没问题后，再者就是上面提到的信任问题，这是10.3系统新加的，很多人容易忽略这一步，官网地址：https://support.apple.com/zh-cn/HT204477

**Comment by LJYes** [comment]
果然是关着的，已经能安装成功了，感谢！

![image](https://user-images.githubusercontent.com/18663185/34969590-7428f2c8-faaa-11e7-8968-3e203db615b0.png)

**Comment by iBcker** [comment]
我建议用个受信的证书吧，这样整对安装的人也比较麻烦。

**Comment by yuxingxin** [comment]
@iBcker 是的，自签证书就是有这个问题，受信证书首推Let’s Encrypt：https://letsencrypt.org/   ，可以参考电子前哨基金会EFF的 Certbot：https://certbot.eff.org/  非常方便，最后做个自动化的证书更新脚本就好啦

**Comment by LJYes** [comment]
说的没错，自签证书对与安装APP来说太过繁琐。目前安卓手机还是无法下载apk安装包，我觉得也可能是证书的问题。由于域名还在审核，部署只能先搁置，等域名审核完，我会总结一下自己遇到的问题。
@iBcker @yuxingxin  谢谢两位的帮助！
