### ISSUE TITLE
小白请教，怎么保持服务常驻啊

### ISSUE THREAD

**Issue by aslanTT** [pluosi/app-host#16]
我用ssh登录的服务器，但是我终端一关闭，服务也断了，这个咋办？

**Comment by iBcker** [comment]
puma 或者 docker

**Comment by yuxingxin** [comment]
这样启动也可以：`rails  s -d`

**Comment by aslanTT** [comment]
我用的rails s，加个-d就没事吗？ @yuxingxin

**Comment by aslanTT** [comment]
试了下rails s -d不行 @yuxingxin

**Comment by iBcker** [comment]
@aslanTT 非要用这个方案的话，可以用 tmux

**Comment by yuxingxin** [comment]
@aslanTT 哦，我的是在Linux上面跑的，不知道你的环境是什么？另外不行的话，有报错吗？你可以把运行的或者错误日志贴出来

**Comment by aslanTT** [comment]
这个我关了，没问题了，谢谢大神们
