### ISSUE TITLE
配https

### ISSUE THREAD

**Issue by supersharenmowang** [pluosi/app-host#17]
你好，请问如何在你的项目上挂https服务？我用的mac系统，项目已经搭建好了，本地也装了apache和nginx，但是不知道如何挂

**Comment by yuxingxin** [comment]
可以参考这里作者发的NGINX配置demo:  #10

**Comment by supersharenmowang** [comment]
nginx 部署在外面，docker 里的东西不用动？这句话我没法理解，是需要移动nginx.conf的路径吗？

**Comment by yuxingxin** [comment]
不需要，NGINX直接代理本机服务地址就可以了，服务就是你本机服务，端口就是docker expose的端口，本机尝试访问 http://localhost:3000试一下 ,如果不希望用3000端口，可以手动修改 docker/launcher 里的`local_port`值

**Comment by supersharenmowang** [comment]
那我还是正常通过rails s来启动服务吗？那如何让我修改过的nginx.conf生效呢？

**Comment by yuxingxin** [comment]
这是属于NGINX的范畴了，你可以执行`nginx -s reload`来让其重新加载配置，当然你也可以重启NGINX

**Comment by supersharenmowang** [comment]
我现在开启了nginx，项目启不了了
rails s                                                                                                              ‹ruby-2.5.0›
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.5.0-p0), codename: Private Caller
* Min threads: 1, max threads: 8
* Environment: development
* Listening on tcp://0.0.0.0:3000
Exiting
Traceback (most recent call last):
	33: from bin/rails:3:in `<main>'
	32: from bin/rails:3:in `load'
	31: from /Users/super/Documents/project/app-host-master/bin/spring:15:in `<top (required)>'
	30: from /Users/super/Documents/project/app-host-master/bin/spring:15:in `require'
	29: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	28: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	27: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	26: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	25: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	24: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	23: from /Users/super/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	22: from /Users/super/Documents/project/app-host-master/bin/rails:9:in `<top (required)>'
	21: from /Users/super/Documents/project/app-host-master/bin/rails:9:in `require'
	20: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	19: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	18: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	17: from /Users/super/.rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	16: from /Users/super/.rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /Users/super/.rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	14: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	13: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	12: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	11: from /Users/super/.rvm/gems/ruby-2.5.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:44:in `start'
	10: from /Users/super/.rvm/gems/ruby-2.5.0/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
	 9: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/rack/handler/puma.rb:69:in `run'
	 8: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
	 7: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/single.rb:87:in `run'
	 6: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/runner.rb:144:in `load_and_bind'
	 5: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:88:in `parse'
	 4: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:88:in `each'
	 3: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:105:in `block in parse'
	 2: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:269:in `add_tcp_listener'
	 1: from /Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:269:in `new'
/Users/super/.rvm/gems/ruby-2.5.0/gems/puma-3.9.1/lib/puma/binder.rb:269:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)

**Comment by yuxingxin** [comment]
从报错的信息看，是因为你的3000端口被占用了，你需要检查下你的端口情况，没问题后再启动项目查看本机服务 http://localhost:3000

**Comment by supersharenmowang** [comment]
我在nginx下面挂了3000的端口

**Comment by supersharenmowang** [comment]
不然我不知道puma如何挂载到nginx下面

**Comment by supersharenmowang** [comment]
我是在nginx下面挂了3000端口，不然我不知道如何在puma挂nginx服务器

**Comment by supersharenmowang** [comment]
你好，我配置好了后执行https://192.168.20.38的时候提示403 Forbidden，
我在nginx上面写的是
location / {
            root   /Users/super/Documents/project/app-host-master/public;
			index index.html index.htm;
        }

**Comment by yuxingxin** [comment]
nginx 配置有问题，参考这里吧： #10

**Comment by iBcker** [comment]
哈哈哈哈哈，没这方面经验的建议上用 docker 的方案

**Comment by supersharenmowang** [comment]
我这个已经好了。现在有个新问题，就是我上传ipa后提示我没法连接到192.168.20.38服务器，这种情况我需要上传plist，我现在不太清楚该怎么上传plist

**Comment by yuxingxin** [comment]
有一个注意的地方是第一次下载安装之前，需要先安装根证书，在安装完证书以后，在设置->通用->关于本机->证书信任设置 中对安装的根证书启用“完全信任”，这样才可以连接到服务器去下载App

**Comment by supersharenmowang** [comment]
ok，已经全部搞定了，非常感谢

**Comment by aslanTT** [comment]
@yuxingxin 还有没有什么别的办法。。。自签证书需要客户端安装根证书，那么多测试设备咋一个个安装。。

**Comment by SuperDannyBoy** [comment]
@supersharenmowang 你好，请问是使用本地服务器搭建https吗？能否告知下如何配置，这边安装了nginx，同时也改了配置文件，但是访问https://192.168.254.20:443浏览器报警告，然后我直接继续访问就进入了Welcome to nginx!的欢迎界面了。
