### ISSUE TITLE
配置https后登录报错

### ISSUE THREAD

**Issue by aslanTT** [pluosi/app-host#18]
https证书是自签名的，域名不是通过DNS解析的，是本地配的hosts

输入用户名和密码后，点击登录，报错：

<img width="813" alt="screen shot 2018-01-15 at 10 37 03 am" src="https://user-images.githubusercontent.com/1904655/34924748-3c899cac-f9e0-11e7-8962-f82d49ca7041.png">

**Comment by iBcker** [comment]
nginx 配错了，请贴一下

**Comment by aslanTT** [comment]
<img width="924" alt="screen shot 2018-01-23 at 9 48 07 am" src="https://user-images.githubusercontent.com/1904655/35253869-91a08398-0022-11e8-9279-7ec229e0325b.png">

@iBcker

**Comment by iBcker** [comment]
试试加上这个
location / 里加上
        proxy_redirect    off;
        proxy_set_header  Host             $http_host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;

**Comment by aslanTT** [comment]
谢谢啦，OK了
