### ISSUE TITLE
登录成功后报错

### ISSUE THREAD

**Issue by WillkYang** [pluosi/app-host#19]
![image](https://user-images.githubusercontent.com/10380145/35102938-594cfd2c-fc9f-11e7-936e-a76c4e6e4b35.png)

**Comment by aslanTT** [comment]
跟我报一样的错
看看我这个https://github.com/pluosi/app-host/issues/18

**Comment by iBcker** [comment]
此问题并不是一个 bug，而是 CSRF 防护
