### ISSUE TITLE
iOS分发自签名证书问题

### ISSUE THREAD

**Issue by yuxingxin** [pluosi/app-host#2]
请问iOS自签名证书该如何配置，现在上传ipa包后下载页面目前只提示说："当前证书无效"

**Comment by iBcker** [comment]
证书直接挂 nginx 上，其实就是 https 的证书。如果你有域名，可以申请letsencrypt的免费证书，如果没有的话，就只能自己签了。如果是自签名证书，iOS 里还得设置信任。

https自签名证书的过程我找了个教程，你可以参考一下
https://blog.imdst.com/li-yong-opensslchuang-jian-zi-qian-ming-de-sslzheng-shu/

**Comment by aslanTT** [comment]
@yuxingxin  @iBcker  嗨，二位大佬，我在腾讯云免费生成了一个证书，有域名，访问网站时候https已经是授信的，但是下载时候说服务器证书无效呢
