### ISSUE TITLE
建议增加一个内网渠道

### ISSUE THREAD

**Issue by sephilex** [pluosi/app-host#21]
其实iOS 的https要求，只是针对plist文件，ipa的URL不强制https

把app-host的服务部署到公网，并加上https，在上传IPA的时候，选择是否添加ipa内网http地址，如果添加，则多生成一个ipa地址为内网http的plist文件，自动生成一个内网的渠道，这样内网测试时就不用信任自签的https证书了。 
安卓也可以增加一个类似的功能，内网就不用再部署一份服务

**Comment by iBcker** [comment]
我没想明白你说的这个有什么意义···

**Comment by sephilex** [comment]
对于内部测试，只需记住一个域名，在公司内网时，大大减少上传和安装时间，对于iOS，还免去信任自签的https证书步骤




| |
邮箱：sephilex@163.com
|

签名由 网易邮箱大师 定制

在2018年02月07日 23:08，iBcker 写道：

我没想明白你说的这个有什么意义···

**Comment by iBcker** [comment]
你内网加个 dns 解析，直接指到内网 ip 就解决速度问题了，信任证书的问题我刚才回答了。

**Comment by zxm9988** [comment]
@sephilex  如果没有内网DNS的话可以写一个把plist 上传到7牛或者阿里云上，然后改下 install_url
