### ISSUE TITLE
HTTPS下 部分资源不能加载，以及 ipa 的路径生成不对

### ISSUE THREAD

**Issue by huanglins** [pluosi/app-host#27]
<img width="1558" alt="2018-04-05 2 02 04" src="https://user-images.githubusercontent.com/10528244/38349508-044b9078-38da-11e8-8fbb-eb11976e76c6.png">
<img width="1136" alt="2018-04-05 2 02 28" src="https://user-images.githubusercontent.com/10528244/38349511-04aef320-38da-11e8-980e-8dd47fc564b0.png">

**Comment by iBcker** [comment]
settings.local.yml 里写上你的域名
