### ISSUE TITLE
安卓包上传后内存不回收。多次上传后内存耗尽，被系统杀掉

### ISSUE THREAD

**Issue by lhr000lhr** [pluosi/app-host#30]
安卓包上传后内存不回收。多次上传后内存耗尽，被系统杀掉

**Comment by iBcker** [comment]
你分多少的内存，我发现是有这个 bug？临时方案可以多分点内存，我发现他涨到一定程度就不涨了。我有空看看怎么把安卓按个泄露内存的库替换掉

**Comment by lhr000lhr** [comment]
机器内存只有512M的，实在是无法运行。_(:з」∠)_希望能尽快解决。只可惜 不会ruby，不然可以帮忙pr。

**Comment by iBcker** [comment]
你配个磁盘swap吧，我尽快改。

**Comment by LLYHMC** [comment]
小白一个，可以教教我怎么使用吗

**Comment by donly** [comment]
> 你配个磁盘swap吧，我尽快改。

请问这个问题修复了吗，不错的项目支持一下

**Comment by iBcker** [comment]
已解决 https://github.com/pluosi/app-host/commit/cde01ee936543f778704f4147629503520ef51d5
