### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by xxzj990** [pluosi/app-host#31]
页面的样式为什么加载不上
![qq](https://user-images.githubusercontent.com/5134154/39558287-ee28f99c-4ebf-11e8-8fb8-079feaa4c342.jpg)

**Comment by iBcker** [comment]
前端配了 nginx？

**Comment by xxzj990** [comment]
@iBcker 没动nginx的配置，镜像下载下来后就修改了一个production 的 secret key，其他配置都没动。用的http

**Comment by Sooyung** [comment]
我这也是同样的问题，把这两个改掉就好些了。感觉nginx的反向代理和静态文件的过滤配置应该是问题的。请问有改好吗@xxzj990 是否可以分享一下经验哦。
![image](https://user-images.githubusercontent.com/2867191/58680642-35f61500-839b-11e9-956e-7bcbad1cc58f.png)

**Comment by xxzj990** [comment]
@Sooyung 没改好
