### ISSUE TITLE
建议:  可以发布一个已经构建好的docker镜像

### ISSUE THREAD

**Issue by yaming116** [pluosi/app-host#33]
如题，我看了一下配置，发现不需要改太多东西，这样会更容易使用一下

**Comment by star7th** [comment]
作者可以去了解下怎么使用hub.docker.com自动从github中生成镜像

**Comment by iBcker** [comment]
docker run --name app_host -v ~/shared:/app/shared -p 3000:8686 -d tinyc/app-host:lastest
