### ISSUE TITLE
IOS 下载

### ISSUE THREAD

**Issue by suyulin** [pluosi/app-host#35]
目前有两个问题:
1. APP下载地址默认是localhost开头,如何修改
![image](https://user-images.githubusercontent.com/6275411/40654506-1af81834-6371-11e8-9aab-291da032cfba.png)
2.IOS的IPA文件如何安装,点击下载 如下图
![image](https://user-images.githubusercontent.com/6275411/40654658-7d39d2f8-6371-11e8-9617-f0f6712990df.png)

**Comment by iBcker** [comment]
settings.local.yml
