### ISSUE TITLE
The change you wanted was rejected.

### ISSUE THREAD

**Issue by zohar-soul** [pluosi/app-host#37]
ip+端口号访问会被强制指向https
然后自行改回http可出现注册页面，然后注册会报这个错误
是什么问题呢？
求指导 谢谢啦

**Comment by lidongzhuo** [comment]
同问

**Comment by iBcker** [comment]
https://github.com/pluosi/app-host/issues/26

**Comment by zohar-soul** [comment]
不能只使用http的吗
我不需要支持ios

**Comment by iBcker** [comment]
@zohar-soul 可以啊，settings 文件里自己配的

**Comment by hack2012** [comment]
经测试是因为默认的nginx.conf中的一个配置导致了请求会由http post 到https 所以浏览器会拒绝。
解决办法：将 docker/nginx.conf 中 proxy_set_header X-Forwarded-Ssl on; 这个配置前面加个# 号即可解决。
