### ISSUE TITLE
想问一下还有没有类似的开源系统？

### ISSUE THREAD

**Issue by mmzhi** [pluosi/app-host#38]
想修改这个系统满足我们企业需求，但是对Ruby不熟悉，想知道这方面的系统，还有没有其他开源方案？

**Comment by iBcker** [comment]
我当初是没有找到，所以才自己写。如果有找到比较好用的也推荐我一下

**Comment by iBcker** [comment]
@jicheng1014 哈哈，fir 主要不支持内部版本部署，企业内部要用不方便。

**Comment by mmzhi** [comment]
@jicheng1014 我们公司也有用fir和蒲公英，但是某些地方都没有满足，所以才想自己开发，目前可以用的开源版本就好像只有这个选择了

**Comment by iBcker** [comment]
@mmzhi 其实 Ruby 还是很好改的，欢迎一起完善~我最近忙成狗了，都没时间继续开发新功能。。。

**Comment by mmzhi** [comment]
目前已有另一个选择：https://github.com/HeadingMobile/fabu.love

**Comment by iBcker** [comment]
@mmzhi fabu 看起来也不是不错的选择，可以选个熟悉的用。毕竟这东西，估计落地后还要自己定制化一点东西
