### ISSUE TITLE
mina deploy 失败

### ISSUE THREAD

**Issue by feiadan** [pluosi/app-host#4]
本地机器调试起来没问题的，用mina部署到服务器（一台iMac）的时候在这一步报错。

不知是什么原因。

![image](https://user-images.githubusercontent.com/6028152/34510277-7dac1eb4-f08d-11e7-84b0-9838294381c1.png)

**Comment by yuxingxin** [comment]
你尝试把`config/secrets.yml`和`config/database.yml`事先拷贝到服务器的config目录，然后再次执行`mina deploy`

**Comment by iBcker** [comment]
楼上正解，并且请确保服务器端的config/secrets.yml的保密性

ps：刚刚更新了 docker 的支持，图省事的可以直接上 docker
