### ISSUE TITLE
curl 上传提示 no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Moonisky** [pluosi/app-host#40]
使用如下命令上传：
`curl --form plat_id=3 --form token=0e0c6e491c42ca7127b1ea04175218ab6144b58a --form file=uat.ipa http://xxx/api/pkgs`

提示错误信息：
`{"error":"no implicit conversion of nil into String"}`

换用如下命令上传：
`curl --form plat_id=3 --form token=0e0c6e491c42ca7127b1ea04175218ab6144b58a --form file=uat.ipa --form file_nick_name="uat_140" http://xxx/api/pkgs`

提示错误信息：
`{"error":"Bundle Id  not match xxx"}` 

网页提交正常。

**Comment by Moonisky** [comment]
--form 上传文件的时候需要加上 `@` = =
close this issue

**Comment by iBcker** [comment]
嗯，参数问题
