### ISSUE TITLE
安装后新建用户报错

### ISSUE THREAD

**Issue by fax001** [pluosi/app-host#43]
![snipaste_2018-09-12_15-01-27](https://user-images.githubusercontent.com/1317574/45407643-a093e300-b69c-11e8-8b63-2832ba664e19.png)

**Comment by trockxi** [comment]
how can i solve this problem?

**Comment by derekibw** [comment]
你是怎么解决的，我用docker运行后也有同样的问题

**Comment by iBcker** [comment]
https://github.com/pluosi/app-host/issues/26

**Comment by derekibw** [comment]
首先说下，我是在macOS10.15.1 下安装的nginx配置，然后以docker的方式运行项目。主要的问题还是Nginx的配置问题，参照 https://xhl.me/archives/set-up-local-https/ 这篇文章逐步配置Nginx后完美解决。

**Comment by hack2012** [comment]
确实存在这个问题，看了N多依然没解决。
