### ISSUE TITLE
上传iOS包，不显示应用icon

### ISSUE THREAD

**Issue by SuperDannyBoy** [pluosi/app-host#46]
本人上传了iOS安装包，但是icon却没有显示出来

**Comment by iBcker** [comment]
是不是没有 AppIcon60x60 或者AppIcon40x40 的图？

**Comment by SuperDannyBoy** [comment]
@iBcker 因为安装包是给ipad使用，所以就获取到logo

**Comment by iBcker** [comment]
iPad？哦，那感觉确实有问题。
你的修改我觉得问题不大~

**Comment by iBcker** [comment]
https://github.com/pluosi/app-host/commit/53a4f80637cdc8b5e29e50b603ecc53bdb1a40e6
