### ISSUE TITLE
希望大佬可以增加安裝包更新內容的備註

### ISSUE THREAD

**Issue by SuperDannyBoy** [pluosi/app-host#47]
希望大佬可以增加安裝包更新內容的備註，這樣有利於不同版本的安裝包查看更新的內容。

**Comment by iBcker** [comment]
好建议~

**Comment by SuperDannyBoy** [comment]
@iBcker 跑迁移报错。

/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'                                                                             
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `each' 
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:1200:in `migrate_without_lock'                                                                                      
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:1150:in `migrate'                                                                                                   
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in `up'   
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in `migrate'                                                                                                    
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in `migrate'                                                                                         
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'                                                             
/usr/local/rvm/gems/ruby-2.5.3/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'                                                                                       
/usr/local/rvm/gems/ruby-2.5.3/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'                                                                                                
/usr/local/rvm/gems/ruby-2.5.3/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'               
/usr/local/rvm/gems/ruby-2.5.3/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'    
/opt/app-host/bin/rails:9:in `require'                                                               
/opt/app-host/bin/rails:9:in `<top (required)>'                                                      
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'             
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'             
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'            
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'                    
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'                 
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'                  
/usr/local/rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'      
/opt/app-host/bin/spring:15:in `require'                                                             
/opt/app-host/bin/spring:15:in `<top (required)>'                                                    
bin/rails:3:in `load'                                                                                
bin/rails:3:in `<main>'                                                                              
Tasks: TOP => db:migrate                                                                             
(See full trace by running task with --trace)

**Comment by SuperDannyBoy** [comment]
@iBcker 你好，部署完之后，发现之前上传的应用无法打开详情页面直接报错
访问的地址路径为：https://www.xxx.com/pkgs/xx
500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by iBcker** [comment]
@SuperDannyBoy 你微信多少，直接聊吧，这个可能要看下 log

**Comment by iBcker** [comment]
@SuperDannyBoy 邮件我联系方式吧 ibcker@me.com
