### ISSUE TITLE
部署后找不到资源

### ISSUE THREAD

**Issue by feiadan** [pluosi/app-host#5]
![image](https://user-images.githubusercontent.com/6028152/34549547-64463eb6-f144-11e7-934f-60614c8997f6.png)
资源文件确实存在

[production.log](https://github.com/pluosi/app-host/files/1602371/production.log)

首次使用puma，多指教！

**Comment by iBcker** [comment]
这个是 nginx 的问题

给你给配置参考

upstream app {
    server 0.0.0.0:3000;
}

server {
    listen   8686;
    server_name 0.0.0.0;
    **root /app/public;**
    index index.html index.htm;

    error_page  404              /404.html;
    error_page  500 502 503 504  /500.html;
    keepalive_timeout 60;

    client_max_body_size 1000m;

    **location ~ ^/(assets|uploads)/  {
        gzip_static on;
        expires max;
        add_header Cache-Control public;
        break;
    }**

    location / {
        proxy_redirect    off;
        proxy_set_header  Host             $http_host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;

        if (!-f $request_filename) {
            proxy_pass http://app;
        }
    }

}
