### ISSUE TITLE
设置web访问的根路径

### ISSUE THREAD

**Issue by langyan1022** [pluosi/app-host#52]
对ruby不熟，在内网历尽千辛万苦的装完之后，并且启动成功
访问路径是 http://ip:3000,
那么问题来了，由于一些原因，需要设置成类似http://ip:3000/apphost 这样的访问方式，
百度无果，请问下应该怎么设置，谢谢了

**Comment by iBcker** [comment]
这个和语言没关系的，nginx 要处理的工作

**Comment by iBcker** [comment]
还有有点想不明白为什么要把 apphost 放在连接后面呢，这样写 nginx 配置感觉比较麻烦呀。干嘛不用一个新的端口或者域名？
