### ISSUE TITLE
api 上传 有渠道参数吗？

### ISSUE THREAD

**Issue by tanpengsccd** [pluosi/app-host#61]
`curl --form plat_id=34 --form file_nick_name=file_nick_name(可选) --form token=69f7dc404e617e4e7cc404d1269e41018af7eb9c --form features=features(可选) --form file=@/xx/xx.ipa https://www.xxx.com/api/pkgs`

我建立了2个渠道，相同的bundle id，想用于分发同bundle id但是不同的ipa。但是上传好像没这个参数

**Comment by iBcker** [comment]
plat_id=34 ?

**Comment by tanpengsccd** [comment]
比如这里2个渠道，我想上传到第二个渠道渠道，这2个渠道我配置的相同bundle id。
![image](https://user-images.githubusercontent.com/13959880/59752484-e6797980-92b4-11e9-92d5-2cc116beac6c.png)

**Comment by iBcker** [comment]
相同 bundleid的plat_id也是不同的呢，你点过去看下浏览器地址栏里的plat_id就知道了

**Comment by iBcker** [comment]
![image](https://user-images.githubusercontent.com/1815400/59825622-1e40f980-9367-11e9-9946-44584e6963e8.png)
这个是 plat_id

**Comment by tanpengsccd** [comment]
哦哦，原来是这样
