### ISSUE TITLE
docker部署方式如何配置ssl

### ISSUE THREAD

**Issue by CNGTZ** [pluosi/app-host#62]
docker部署方式如何配置ssl
按照第一种方式运行了docker，怎么配置ssl？有没有详细的教程啊？

**Comment by tanpengsccd** [comment]
看看这篇文章 https://juejin.im/post/5d09ff7ef265da1b897ad460

**Comment by iBcker** [comment]
嗯，nginx 也可以查看这里 https://github.com/pluosi/app-host/issues/17
