### ISSUE TITLE
./docker/launcher bootstrap -v  运行这一命令后，提示以下错误，请问如何解决？

### ISSUE THREAD

**Issue by CNGTZ** [pluosi/app-host#63]
./docker/launcher bootstrap -v  运行这一命令后，提示以下错误，请问如何解决？
Step 13/16 : RUN rake db:migrate
 ---> Running in 2f93aac55905

/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
/usr/local/bundle/gems/rack-2.0.6/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
 ---> 9f64c259f793
Removing intermediate container 2f93aac55905
Step 14/16 : RUN rake assets:precompile
 ---> Running in f15afbfd0587

/app/config/initializers/rack.rb:3: warning: already initialized constant Rack::Multipart::Parser::BUFSIZE
/usr/local/bundle/gems/rack-2.0.6/lib/rack/multipart/parser.rb:8: warning: previous definition of BUFSIZE was here
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
I, [2019-06-20T06:16:39.670026 #9]  INFO -- : Writing /app/public/assets/application-fe589a5031808489c02a7ba2f9c2fcc05784a2c83272d71ffcc0217dd7710a5c.js
I, [2019-06-20T06:16:39.670585 #9]  INFO -- : Writing /app/public/assets/application-fe589a5031808489c02a7ba2f9c2fcc05784a2c83272d71ffcc0217dd7710a5c.js.gz
I, [2019-06-20T06:16:45.079841 #9]  INFO -- : Writing /app/public/assets/application-d1430be290bd6d2836f130d4ea0036584a714f5796a82dd0918f5fa99f7e70c7.css
I, [2019-06-20T06:16:45.080186 #9]  INFO -- : Writing /app/public/assets/application-d1430be290bd6d2836f130d4ea0036584a714f5796a82dd0918f5fa99f7e70c7.css.gz
I, [2019-06-20T06:16:45.080537 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-13634da87d9e23f8c3ed9108ce1724d183a39ad072e73e1b3d8cbf646d2d0407.eot
I, [2019-06-20T06:16:45.081006 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-13634da87d9e23f8c3ed9108ce1724d183a39ad072e73e1b3d8cbf646d2d0407.eot.gz
I, [2019-06-20T06:16:45.081511 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-fe185d11a49676890d47bb783312a0cda5a44c4039214094e7957b4c040ef11c.woff2
I, [2019-06-20T06:16:45.082060 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-a26394f7ede100ca118eff2eda08596275a9839b959c226e15439557a5a80742.woff
I, [2019-06-20T06:16:45.082967 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-e395044093757d82afcb138957d06a1ea9361bdcf0b442d06a18a8051af57456.ttf
I, [2019-06-20T06:16:45.083655 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-e395044093757d82afcb138957d06a1ea9361bdcf0b442d06a18a8051af57456.ttf.gz
I, [2019-06-20T06:16:45.084097 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-42f60659d265c1a3c30f9fa42abcbb56bd4a53af4d83d316d6dd7a36903c43e5.svg
I, [2019-06-20T06:16:45.084732 #9]  INFO -- : Writing /app/public/assets/bootstrap/glyphicons-halflings-regular-42f60659d265c1a3c30f9fa42abcbb56bd4a53af4d83d316d6dd7a36903c43e5.svg.gz
I, [2019-06-20T06:16:45.115535 #9]  INFO -- : Writing /app/public/assets/normalize-rails/normalize-d614e0bcbbd9f3542ef8b53f8a33aac3a58291c5f990c933a30aaa505c816df1.css
I, [2019-06-20T06:16:45.115751 #9]  INFO -- : Writing /app/public/assets/normalize-rails/normalize-d614e0bcbbd9f3542ef8b53f8a33aac3a58291c5f990c933a30aaa505c816df1.css.gz

**Comment by iBcker** [comment]
好像没报错吧，都是 log 呢

**Comment by CNGTZ** [comment]
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
现在剩下这个问题了   我初始化完成后，运行docker    没有起来

**Comment by iBcker** [comment]
Yarn executable was not detected in the system.
这个提示可以忽略
