### ISSUE TITLE
这个解析包很慢啊。单线程问题吗？

### ISSUE THREAD

**Issue by chihong2012** [pluosi/app-host#68]
这个解析包很慢啊。单线程问题吗？

希望完善下

**Comment by iBcker** [comment]
是有这个问题

**Comment by LLYHMC** [comment]
能教我一下怎么搞这个东西吗

**Comment by chhsh122** [comment]
确实 我发布在服务器上面 很慢 单线程问题

**Comment by iBcker** [comment]
嗯呢，是有这个问题，可以把内存调大点，计划改一版放到后台处理了。

**Comment by iBcker** [comment]
已解决 https://github.com/pluosi/app-host/commit/cde01ee936543f778704f4147629503520ef51d5
