### ISSUE TITLE
上传iOS包报错

### ISSUE THREAD

**Issue by WillkYang** [pluosi/app-host#7]
在mac上使用非docker方式运行后，包上传到服务器后报错
![报错截图](https://user-images.githubusercontent.com/10380145/34609382-79c3abfc-f257-11e7-906d-f1f4c935376d.png)

**Comment by iBcker** [comment]
已修复: [73c5be0c](https://github.com/pluosi/app-host/commit/173c5be0cb67355fc1271f56e02ceff1c8dbc9de)
