### ISSUE TITLE
Nginx设置端口代理后，下载页面二维码不能访问

### ISSUE THREAD

**Issue by LiuJiangc** [pluosi/app-host#76]
因为要配置https，用到Nginx。下载页面的二维码内容是设置代理前的url，请问这个要如何解决呢

**Comment by iBcker** [comment]
setting.local.yml 改一下

**Comment by LiuJiangc** [comment]
改了setting.local.yml ，Nginx把默认的路径http://localhost:3000代理成https://xxx.com:12345这样的，下载按钮是指向setting.local.yml 里的配置，二维码就是http://localhost:3000

**Comment by LiuJiangc** [comment]
我改了一下生成二维码的方法的传入值，二维码内容已经是当前页面的url了

**Comment by LiuJiangc** [comment]
请问一下，我是用源码允许在Centos7上，该如何设置开机启动

**Comment by LiuJiangc** [comment]
@iBcker
