### ISSUE TITLE
ios 无法下载

### ISSUE THREAD

**Issue by reancool** [pluosi/app-host#77]
自己手动配置了一个 plist,就可以了.
创建工程时,类型已经选择ios.
查看了一下html代码,下载地址并没有修改为 'itms-services 这种类型.而直接是一个*.ipa下载地址
估计是 plat_name 没有获取,
我使用docker创建的.安卓可以正常使用.

**Comment by iBcker** [comment]
配https
ps：
你看到的是电脑浏览器的地址，手机上会是另一个

**Comment by reancool** [comment]
已经配置https了

**Comment by reancool** [comment]
我用ios 下载的时候 提示,未认证,但是自己写一个 plist 可以下载
