### ISSUE TITLE
我上传成功了，如果点击下载的话会自动跳转到locahost:3000端口后浏览器提示拒绝访问

### ISSUE THREAD

**Issue by henlei153** [pluosi/app-host#81]
我创建好了证书，现在如何将证书安装在app-host上呢？

**Comment by LLYHMC** [comment]
可以教教是怎么部署这个的吗

**Comment by henlei153** [comment]
> 可以教教是怎么部署这个的吗

我还没弄好呢。。。怕给你带错路了，不过这个作者快回复我呀

**Comment by LLYHMC** [comment]
不怕啊，我小白一个需要一个大佬解惑，求教。QQ825081219

**Comment by henlei153** [comment]
解决了，在settting.local.yml文件中修改localhost为本机ip，就可以下载了
