### ISSUE TITLE
关于ios下载问题

### ISSUE THREAD

**Issue by henlei153** [pluosi/app-host#87]
我在nginx上挂上了https后，通过proxy代理到后端3000端口，为何点击下载是通过后端3000端口下载的？然后提示我：

**Comment by henlei153** [comment]
此网站我发提供安全链接

**Comment by henlei153** [comment]
点击下载会跳转到https://服务器ip:3000端口，但是https是加在nginx的443端口上，然后就提示网站不安全，难道需要将证书添加到3000端口上？那么app-host如何添加证书

**Comment by yeducom** [comment]
> 我在nginx上挂上了https后，通过代理到到3000端口，为什么点击下载是通过3000端口下载的？然后提示我：

你可以尝尝访问么

**Comment by yeducom** [comment]
> 点击下载会跳转到[https://服务器ip:3000端口，但是https是加在nginx的443端口上，然后就提示网站不安全，难道需要将证书添加到3000端口上？app-host如何添加证书](https://%E6%9C%8D%E5%8A%A1%E5%99%A8ip:3000%E7%AB%AF%E5%8F%A3%EF%BC%8C%E4%BD%86%E6%98%AFhttps%E6%98%AF%E5%8A%A0%E5%9C%A8nginx%E7%9A%84443%E7%AB%AF%E5%8F%A3%E4%B8%8A%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%B1%E6%8F%90%E7%A4%BA%E7%BD%91%E7%AB%99%E4%B8%8D%E5%AE%89%E5%85%A8%EF%BC%8C%E9%9A%BE%E9%81%93%E9%9C%80%E8%A6%81%E5%B0%86%E8%AF%81%E4%B9%A6%E6%B7%BB%E5%8A%A0%E5%88%B03000%E7%AB%AF%E5%8F%A3%E4%B8%8A%EF%BC%9Fapp-host%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E8%AF%81%E4%B9%A6)
我也遇到这个问题 ，兄弟 你那边是怎么解决的

**Comment by iBcker** [comment]
修改下 settings.local.yml ，把你域名写进去就行

**Comment by henlei153** [comment]
> > 点击下载会跳转到[https://服务器ip:3000端口，但是https是加在nginx的443端口上，然后就提示网站不安全，难道需要将证书添加到3000端口上？app-host如何添加证书](https://%E6%9C%8D%E5%8A%A1%E5%99%A8ip:3000%E7%AB%AF%E5%8F%A3%EF%BC%8C%E4%BD%86%E6%98%AFhttps%E6%98%AF%E5%8A%A0%E5%9C%A8nginx%E7%9A%84443%E7%AB%AF%E5%8F%A3%E4%B8%8A%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%B1%E6%8F%90%E7%A4%BA%E7%BD%91%E7%AB%99%E4%B8%8D%E5%AE%89%E5%85%A8%EF%BC%8C%E9%9A%BE%E9%81%93%E9%9C%80%E8%A6%81%E5%B0%86%E8%AF%81%E4%B9%A6%E6%B7%BB%E5%8A%A0%E5%88%B03000%E7%AB%AF%E5%8F%A3%E4%B8%8A%EF%BC%9Fapp-host%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E8%AF%81%E4%B9%A6)
> > 我也遇到这个问题 ，兄弟 你那边是怎么解决的

作者说在settings.local.yml中填写域名，不过下载只是由ip变成了域名，还是提示“此网站无法提供安全链接”
