### ISSUE TITLE
Docker 安装报错 -bash: bootstrap: command not found

### ISSUE THREAD

**Issue by shixueqian** [pluosi/app-host#9]
我用mac部署app-host，按照文档的安装提示安装，
第一步我用的git clone https://github.com/pluosi/app-host.git /opt/app-host 下载的，文档的那个命令中的链接貌似没有权限。。。。
然后在执行  ./docker/launcher bootstrap -v  的时候出错了，
-bash: bootstrap: command not found

请问下是有什么依赖没有安装么？

**Comment by iBcker** [comment]
请问你是什么环境？

**Comment by shixueqian** [comment]
之前的问题的原因是Docker没有安装。。。（请原谅我不太了解这个）
现在已经成功部署了。
对了，执行完./docker/launcher bootstrap -v之后，需要将/opt/app-host/shared这个文件夹在docker中设置共享（这个操作在命令的log中有提示）。
感谢作者

**Comment by iBcker** [comment]
在 docker 客户端里改
![image](https://user-images.githubusercontent.com/1815400/34859336-8ee40e44-f790-11e7-93ee-47f3f81d8ee8.png)
