### ISSUE TITLE
如果支持把上传的应用包(ipa，apk)使用七牛、阿里等云存储平台？

### ISSUE THREAD

**Issue by YuYongzhi** [pluosi/app-host#91]
由于内网速度限制，希望能够支持把上传的应用包放到其他云存储平台上，比如七牛、阿里等。
或者如何修改代码，使之支持？谢谢

**Comment by iBcker** [comment]
首先内网的部署放到公网有点奇怪
但是，如果真需要的话，可以修改 PkgUploader.rb 文件，用这个 gem 增加支持到七牛
https://github.com/huobazi/carrierwave-qiniu
