### ISSUE TITLE
管理员问题

### ISSUE THREAD

**Issue by wangchaoforever** [pluosi/app-host#94]
默认的管理员的邮箱和密码是多少来着？？？

**Comment by lovesora** [comment]
第一次会提示创建admin用户

**Comment by yeducom** [comment]
> 默认的管理员的邮箱和密码是多少来着？？？

方便教教怎么部署么

**Comment by wangchaoforever** [comment]
> > 默认的管理员的邮箱和密码是多少来着？？？
> 
> 方便教教怎么部署么

兄弟，怎么联系？

**Comment by yeducom** [comment]
> > > 默认的管理员的邮箱和密码是多少来着？？？
> > 
> > 
> > 方便教教怎么部署么
> 
> 兄弟，怎么联系？

weixin y16621063561y

**Comment by yeducom** [comment]
> > > 默认的管理员的邮箱和密码是多少来着？？？
> > 
> > 
> > 方便教教怎么部署么
> 
> 兄弟，怎么联系？

非常 感谢了
weixin y1219628211y
