### ISSUE TITLE
code422 怎么处理呢

### ISSUE THREAD

**Issue by yeducom** [pluosi/app-host#95]
nginx 配置 ：
upstream dapp{
	server 192.168.4.119:3000; 
}

server {
	         listen       443;     
         server_name dapp.deerbus.net;
         ssl                     on;
         ssl_certificate         /etc/nginx/conf.d/ssl/deerbus.net.pem;
         ssl_certificate_key     /etc/nginx/conf.d/ssl/deerbus.net.key;
         location / {          
         proxy_pass http://dapp;
     }

}

浏览器请求： 
Request URL:http://192.168.4.119:3000/sessions
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:192.168.4.119:3000

这个怎么修改呢

**Comment by lcb1208** [comment]
同问+1

**Comment by iBcker** [comment]
https://github.com/pluosi/app-host/issues/26

**Comment by iBcker** [comment]
```
location / {
  proxy_pass http://dapp;
}
```

===>

```
location / {
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_pass http://dapp;
}
```

**Comment by hack2012** [comment]
> ```
> location / {
>   proxy_pass http://dapp;
> }
> ```
> 
> ===>
> 
> ```
> location / {
>     proxy_set_header        Host $host;
>     proxy_set_header        X-Real-IP $remote_addr;
>     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header        X-Forwarded-Proto $scheme;
>     proxy_pass http://dapp;
> }
> ```

测试了，没有用处。 centos系统

**Comment by lcb1208** [comment]
`` upstream apphost{
server **ip**;
}
    # HTTPS server
    #
    server {
        listen       443 ssl;
        server_name  ip;
        
       
        #access_log /usr/local/log/nginx/access.log;
        ssl_certificate      /usr/local/sslcert/aa.crt;
        ssl_certificate_key  /usr/local/sslcert/aa.key;

	ssl on;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        location / { 
           proxy_redirect off;
	   proxy_set_header Host $http_host;
	   proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
           proxy_set_header X-Forwarded-Proto $scheme;
 	   proxy_pass http://**ip**:**port**/;  #docker 服务的地址
        }
	 location /certs {
            root /usr/local/sslcert/;
        }
    }

**Comment by lcb1208** [comment]
已解决
 upstream apphost{
server **ip**;
}
    # HTTPS server
    #
    server {
        listen       443 ssl;
        server_name  ip;
        
       
        #access_log /usr/local/log/nginx/access.log;
        ssl_certificate      /usr/local/sslcert/aa.crt;
        ssl_certificate_key  /usr/local/sslcert/aa.key;

	ssl on;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        location / { 
           proxy_redirect off;
	   proxy_set_header Host $http_host;
	   proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
           proxy_set_header X-Forwarded-Proto $scheme;
 	   proxy_pass http://**ip**:**port**/;  #docker 服务的地址
        }
	 location /certs {
            root /usr/local/sslcert/;
        }
    }
