### ISSUE TITLE
请问如何设置setting.local.yml

### ISSUE THREAD

**Issue by henlei153** [pluosi/app-host#98]
以下是我的nginx配置
server {
    listen 443;
    server_name  app.****.com;
    client_max_body_size 200m;

    ssl on;
    access_log /var/log/nginx/access.log;
    ssl_certificate /key/app.***.com.pem;
    ssl_certificate_key /key/app.***.com.key;

    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass http://192.168.0.185:3000;  #docker 服务的地址
    }
}

server {
    listen 80;
    server_name app.***.com;
    rewrite ^(.*)$  https://$host$1 permanent;
}

这是setting.local.yml配置
PROTOCOL: "http://"
HOST: "app.***.com:3000"

# SECRET_KEY_BASE: "可以运行rake secret,docker用户会自动生成，可忽略"

当我将setting.local.yml中设置为http时安卓可以下载，ios提示证书无效
当我将setting.local.yml设置为https，pc点击下载页面提示此网站无法提供安全链接，手机端无提示，服务器端报错：HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.

**Comment by henlei153** [comment]
@iBcker 请问一下，这个问题怎么解决

**Comment by devcxm** [comment]
可以参考下我的配置

```nginx
upstream app_host_server {
    server 127.0.0.1:3000;
}
server {
    listen       80;
    server_name app.site;
    return 301 https://$http_host$request_uri;
}

server {
    listen       443 ssl;
    server_name  app.site;
    root  /data/services/app-host/shared/public;
    ssl_certificate      /etc/letsencrypt/live/app.site-0001/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/app.site-0001/privkey.pem;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    client_max_body_size 1000m;

    location ~ ^/(uploads)/  {
        gzip_static on;
        expires max;
        add_header Cache-Control public;
        break;
    }
    
    location / {
        proxy_pass   http://app_host_server;
        index  index.html index.htm;

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}
```


```yml
PROTOCOL: "https://"
HOST: "app.site"
```

**Comment by henlei153** [comment]
我现在的情况是请求会通过nginx的https请求，跳转下载链接后变http，跳转到后端3000端口下载，问题是如何让它通过nginx下载，而不是在3000端口下载

**Comment by devcxm** [comment]
@henlei153 

我这个配置就是啊，根目录设置到public，匹配到`uploads`路径就不会转发请求到3000

```nginx
root  /data/services/app-host/shared/public;

-------

location ~ ^/(uploads)/  {
        gzip_static on;
        expires max;
        add_header Cache-Control public;
        break;
}


```

**Comment by henlei153** [comment]
谢谢，我试试，我还以为要调app-host

**Comment by henlei153** [comment]
> @henlei153
> 
> 我这个配置就是啊，根目录设置到public，匹配到`uploads`路径就不会转发请求到3000
> 
> ```nginx
> root  /data/services/app-host/shared/public;
> 
> -------
> 
> location ~ ^/(uploads)/  {
>         gzip_static on;
>         expires max;
>         add_header Cache-Control public;
>         break;
> }
> ```

你好，我用了你的nginx配置还是跳转了3000端口

**Comment by devcxm** [comment]
> > @henlei153
> > 我这个配置就是啊，根目录设置到public，匹配到`uploads`路径就不会转发请求到3000
> > ```nginx
> > root  /data/services/app-host/shared/public;
> > 
> > -------
> > 
> > location ~ ^/(uploads)/  {
> >         gzip_static on;
> >         expires max;
> >         add_header Cache-Control public;
> >         break;
> > }
> > ```
> 
> 你好，我用了你的nginx配置还是跳转了3000端口

不应该啊，这是nginx的配置问题，让你公司的后端同事帮你看看。
